routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return view('welcome');
});
	
Route::resource('transactions', 'TransactionsController', ['middleware' => 'auth']);
Route::resource('categories', 'CategoriesController', ['middleware' => 'auth']);

resources/views/partials/errors.blade.php
<div id="errors_notification" v-if="showErrorsNotification" class="bg-red-lightest border border-red-light text-red-dark px-4 py-3 rounded relative" role="alert">
  <strong class="font-bold">Oops!</strong>
  <span class="block sm:inline">Seems like we have some errors right here.</span>
  <span @click="hideMessage" class="absolute pin-t pin-b pin-r px-4 py-3">
    <svg class="fill-current h-6 w-6 text-red" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
  </span>

  @foreach ($errors->all() as $error)
    <div class="m-3 flex-auto border-red rounded">
      {{ $error }}
    </div>
  @endforeach
</div>

<script>
    var errors_notification = new Vue({
      el: '#errors_notification',
      data: {
        showErrorsNotification: {{ $errors->any() ? 'true' : 'false' }}
      },
      methods: {
        hideMessage() {
          this.showErrorsNotification = false;
        }
      }
    });
</script>

resources/views/partials/nav.blade.php
<nav id="navbar" class="flex items-center justify-between flex-wrap bg-blue p-6 rounded">

    <div class="flex items-center flex-no-shrink text-white mr-6">
        <span class="text-xl">ExMan Pro</span>
    </div>

    <div class="block lg:hidden">
        <button @click="toggleMenu" class="flex items-center px-3 py-2 border rounded text-blue-lighter border-blue-light hover:text-white hover:border-white">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
        </button>
    </div>

    <div :class="['w-full block flex-grow lg:flex lg:items-center lg:w-auto', {'xs:hidden' : ! menuVisible}]">
        <div class="text-sm lg:flex-grow">
            <!-- Authentication Links -->
            @guest
                <a href="{{ route('login') }}" class="block mt-4 lg:inline-block lg:mt-0 text-blue-lighter hover:text-white mr-4">Login</a>
                <a href="{{ route('register') }}" class="block mt-4 lg:inline-block lg:mt-0 text-blue-lighter hover:text-white mr-4">Register</a>
            @else

            <div>
                <a href="{{ route('transactions.index') }}" class="block mt-4 lg:inline-block lg:mt-0 text-blue-lighter hover:text-white mr-4 no-underline">Expenses</a>
                <a href="{{ route('transactions.create') }}" class="block mt-4 lg:inline-block lg:mt-0 text-blue-lighter hover:text-white mr-4 no-underline">Add Expenses</a>

                {{-- <a href="{{ route('categories.index') }}" class="block mt-4 lg:inline-block lg:mt-0 text-blue-lighter hover:text-white mr-4 no-underline">Categories</a> --}}
                {{-- <a href="{{ route('categories.create') }}" class="block mt-4 lg:inline-block lg:mt-0 text-blue-lighter hover:text-white mr-4 no-underline">Add Category</a> --}}
            </div>
        </div>
        <div>
           <a href="{{ route('logout') }}" class="inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-blue hover:bg-white mt-4 lg:mt-0" 
                    onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                    Logout
                </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form> 
        </div>
            @endguest

</div>
</nav>

<script>
    new Vue({
        el: '#navbar',

        data: {
            menuVisible: false
        },

        methods: {
            toggleMenu() {
                if (this.menuVisible)
                {
                    this.menuVisible = false;
                } else {
                    this.menuVisible = true;
                }
            }
        }
    });
</script>

resources/views/partials/success.blade.php
<div id="success_notification" v-if="showSuccessNotification" class="bg-green-lightest border border-green-light text-green-dark px-4 py-3 rounded relative" role="alert">
  <strong class="font-bold">Great!</strong>
  <span class="block sm:inline">That was a success.</span>
  <span @click="hideMessage()" class="absolute pin-t pin-b pin-r px-4 py-3">
    <svg class="fill-current h-6 w-6 text-green" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
  </span>

  <div class="m-3 flex-auto border-green rounded">
    {{ session('success') }}
  </div>
</div>

<script>
    var success_notification = new Vue({
      el: '#success_notification',
      data: {
        showSuccessNotification: {{ session()->has('success') ? 'true' : 'false' }}
      },
      methods: {
        hideMessage() {
          this.showSuccessNotification = false;
        }
      }
    });
</script>