routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return view('welcome');
});
	
Route::resource('transactions', 'TransactionsController', ['middleware' => 'auth']);
Route::resource('categories', 'CategoriesController', ['middleware' => 'auth']);

app/Http/Controllers/Api/TransactionsController.php
<?php

namespace App\Http\Controllers\Api;

use App\Transaction;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class TransactionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Placeholder
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // Placeholder
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated_inputs = $this->validate($request, $this->validationRules());

        Transaction::create($validated_inputs + ['user_id' => Auth::user()->id]);

        return response()->json([
            'data' => ['message' => 'resource created successfully']
        ], 201);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $transaction = Transaction::with('category')->find($id);

        if (! $transaction) {
            return response()->json(['errors' => ["This resource instance doesn't exist"]], 404);
        }

        return response()->json(['data' => $transaction->toArray()]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // Placeholder
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validated_inputs = $this->validate($request, $this->validationRules());

        $transaction = Transaction::find($id);

        if (! $transaction) {
            return response()->json(['errors' => ["This resource instance doesn't exist"]], 404);
        }

        $transaction->fill($validated_inputs)->save();

        return response()->json([
            'data' => $transaction->toArray(), 
            'message' => 'resource updated successfully'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $transaction = Transaction::find($id);

        if (! $transaction) {
             return response()->json(['errors' => ["This resource instance doesn't exist"]], 404);
        }

        $transaction->delete();

        return response()->json(['message' => 'resource destroyed successfully']);
    }

    protected function validationRules()
    {
        return [
            'category_id' => 'required|exists:categories,id',
            'amount' => 'required|numeric',
            'date' => 'required',
            'description' => 'required|max:255',
            'notes' => 'max:255',
            'place' => 'max:255',
        ];   
    }
}

app/Http/Controllers/TransactionsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Transaction;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class TransactionsController extends Controller
{
	public function index()
	{
		return view('transactions.index', [
			'transactions' => Transaction::all()
		]);
	}

	public function show(Transaction $transaction)
	{
		return view('transactions.show', compact('transaction'));	
	}

    public function create()
    {
        return view('transactions.create', ['categories' => Category::all()]);    
    }

    public function store()
    {
        $validated_inputs = $this->validate(request(), $this->validationRules());

    	Transaction::create($validated_inputs + ['user_id' => Auth::user()->id]);

    	return redirect()->route('transactions.index');
    }

    public function edit(Transaction $transaction)
    {
        $categories = Category::all();

        return view('transactions.edit', compact('transaction', 'categories'));
    }

    public function update(Request $request, Transaction $transaction)
    {
        $validated_inputs = $this->validate($request, $this->validationRules());

    	$transaction->fill($validated_inputs)->save();

    	return redirect()->route('transactions.index');
    }

    public function destroy($transaction)
    {
    	Transaction::destroy($transaction);

    	return redirect()->route('transactions.index');
    }

    protected function validationRules()
    {
        return [
            'category_id' => 'required|exists:categories,id',
            'amount' => 'required|numeric',
            'date' => 'required',
            'description' => 'required|max:255',
            'notes' => 'max:255',
            'place' => 'max:255',
        ];
    }
}

resources/views/transactions/create.blade.php
@extends('layouts.app')

@section('content')

  @include('transactions.form')

@endsection

resources/views/transactions/edit.blade.php
@extends('layouts.app')

@section('content')

  @include('transactions.form', ['edit' => true])

@endsection

resources/views/transactions/form.blade.php
<form method="post" action="{{ ($edit ?? false) ? route('transactions.update', [$transaction->id]) : route('transactions.store') }}">
		
  {{ csrf_field() }}
  
  @if ($edit ?? false)
    {{ method_field('patch') }}
  @endif

  <div class="md:flex">
    <div class="w-1/2 m-3" id="datepicker">
      <label class="label">Date</label>
        <date-picker name="date" value="{{ $transaction->date ?? date('m/d/Y') }}" input-class="text-field hover:border-blue border-blue-lighter"></date-picker>
    </div>
    
    <div class="w-1/2 m-3">
      <label class="label">Category</label>
      <select name="category_id" class="text-field hover:border-blue border-blue-lighter">
        
        @foreach($categories as $category)
          <option value="{{ $category->id }}">{{ $category->name }}</option>
        @endforeach
        
      </select>
    </div>
  </div>
  
  <div class="md:flex">
    <div class="m-3 flex-auto">
      <label class="label">Description</label>
      <input type="text" name="description" class="text-field hover:border-blue border-blue-lighter" value="{{ $transaction->description ?? '' }}">
    </div>
  </div>
  
  <div class="md:flex">
    <div class="m-3 flex-auto">
      <label class="label">Notes</label>
      <textarea type="text" name="notes" rows="3" class="text-field hover:border-blue border-blue-lighter">{{ $transaction->notes ?? '' }}</textarea>
    </div>
  </div>
  
  <div class="md:flex">
    <div class="m-3 flex-auto">
      <label class="label">Place</label>
      <input type="text" name="place" class="text-field hover:border-blue border-blue-lighter" value="{{ $transaction->place ?? '' }}">
    </div>
  </div>
  
  <div class="md:flex">
    <div class="m-3 flex-auto">
      <label class="label">Amount</label>
      <input type="text" name="amount" class="text-field hover:border-blue border-blue-lighter" value="{{ $transaction->amount ?? '' }}">
    </div>
  </div>
  
  <div class="md:flex">
    <div class="m-3 flex-auto">
      <button type="submit" class="btn btn-blue">Save</button>
    </div>
  </div>
  
</form>

<script>
  new Vue({
    el: '#datepicker'
  });
</script>

resources/views/transactions/index.blade.php
@extends('layouts.app')

@section('content')
	
	<div class="overflow-x-scroll">
		<table>

			<tr class="w-full">
				<th class="w-1/6 border-b-2 p-2 border-blue-lighter">Date</th>
				<th class="w-3/6 border-b-2 p-2 border-blue-lighter">Description</th>
				<th class="w-1/6 border-b-2 p-2 border-blue-lighter">Category</th>
				<th class="w-1/6 border-b-2 p-2 border-blue-lighter">Amount</th>
				<th class="w-1/6 bg-grey-lighter"></th>
			</tr>
			
			@foreach($transactions as $expense)	
			<tr class="w-full">
				<td class="w-1/6 p-2 text-center">{{ $expense->date }}</td>
				<td class="w-3/6 p-2 text-center">{{ $expense->description }}</td>
				<td class="w-1/6 p-2 text-center">{{ $expense->category->name }}</td>
				<td class="w-1/6 p-2 text-center">{{ $expense->amount }} JD</td>
				<td class="w-1/6 p-2 text-center flex justify-between">

					<form method="GET" action="{{ route('transactions.edit', [$expense->id]) }}">
						<button class="btn text-grey-dark hover:bg-blue-lighter mx-2">E</button>
					</form>

					<form method="POST" action="{{ route('transactions.destroy', [$expense->id]) }}">
						{{ csrf_field() }}
						{{ method_field('delete') }}
						<button type="submit" class="btn text-grey-dark hover:bg-red-lighter mx-2">D</button>
					</form>
				</td>
			</tr>
			@endforeach

		</table>		
	</div>

	{{-- {{ $transactions->links() }} --}}
@endsection

resources/views/transactions/show.blade.php
@extends('layouts.app')

@section('content')
			  
  <div class="md:flex">
    <div class="w-1/2 m-3 mb-6">
      <h3 class="text-base text-grey-darker py-2 border-b-2">Date</h3>
      <p class="text-lg pt-3">{{ $transaction->date }}</p>
    </div>
    
    <div class="w-1/2 m-3 mb-6">
      <h3 class="text-base text-grey-darker py-2 border-b-2">Category</h3>
      <p class="text-lg pt-3">{{ $transaction->category->name }}</p>
    </div>
  </div>
  
  <div class="md:flex">
    <div class="m-3 mb-6 flex-auto">
      <h3 class="text-base text-grey-darker py-2 border-b-2">Description</h3>
      <p class="text-lg pt-3">{{ $transaction->description }}</p>
    </div>
  </div>
  
  <div class="md:flex">
    <div class="m-3 mb-6 flex-auto">
      <h3 class="text-base text-grey-darker py-2 border-b-2">Notes</h3>
      <p class="text-lg pt-3">{{ $transaction->notes }}</p>
    </div>
  </div>
  
  <div class="md:flex">
    <div class="m-3 mb-6 flex-auto">
      <h3 class="text-base text-grey-darker py-2 border-b-2">Place</h3>
      <p class="text-lg pt-3">{{ $transaction->place }}</p>
    </div>
  </div>
  
  <div class="md:flex">
    <div class="m-3 mb-6 flex-auto">
      <h3 class="text-base text-grey-darker py-2 border-b-2">Amount</h3>
      <p class="text-lg pt-3">{{ $transaction->amount }} JD</p>
    </div>
  </div>
  
  <div class="md:flex">
    <div class="m-3 mb-6 mt-5">
      <a href="{{ route('transactions.edit', [$transaction->id]) }}" class="btn btn-blue no-underline">Edit</a>
    </div>

    <div class="m-3 mb-6 mt-1">
    	<form method="post" action="{{ route('transactions.destroy', [$transaction->id]) }}">
    		{{ csrf_field() }}
    		{{ method_field('delete') }}
	    	<input type="submit" class="btn btn-red no-underline cursor-pointer" value="Delete">
    	</form>
    </div>
  </div>

@endsection