routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return view('welcome');
});
	
Route::resource('transactions', 'TransactionsController', ['middleware' => 'auth']);
Route::resource('categories', 'CategoriesController', ['middleware' => 'auth']);

app/Models/Category.php
<?php

namespace App;

use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = [];

    public function user()
    {
    	return $this->belongsTo(User::class);
    }

    public function scopeForAuthedUser($query)
    {
    	return $query->where('user_id', Auth::user()->id);
    }
}

app/Http/Controllers/Api/CategoriesController.php
<?php

namespace App\Http\Controllers\Api;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @todo  Paginate response
     * 
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return response()->json(Category::forAuthedUser()->get()->toArray());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:33'
        ]);

        $category = Category::create($request->all() + ['user_id' => Auth::user()->id]);

        return response()->json([
            'data' => ['message' => 'resource created successfully']
        ], 201);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::forAuthedUser()->find($id);

        if (! $category) {
            return response()->json(['errors' => ["This resource instance doesn't exist"]], 404);
        }

        return response()->json(['data' => $category->toArray()]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|max:33'
        ]);
        
        $category = Category::forAuthedUser()->find($id);

        if (! $category) {
            return response()->json(['errors' => ["This resource instance doesn't exist"]], 404);
        }

        $category->fill($request->all())->save();

        return response()->json([
            'data' => $category->toArray(), 
            'message' => 'resource updated successfully'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::forAuthedUser()->find($id);

        if (! $category) {
             return response()->json(['errors' => ["This resource instance doesn't exist"]], 404);
        }

        $category->delete();

        return response()->json(['message' => 'resource destroyed successfully']);        
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
	public function index()
	{
		return view('categories.index', [
			'categories' => Category::ForAuthedUser()->get()
		]);
	}

	public function show($category)
	{  
		return view('categories.show', [
			'category' => Category::ForAuthedUser()->findOrFail($category)
		]);
	}

    public function store(Request $request)
    {
        $this->validate($request, [
            'user_id' => 'required|exists:users,id',
            'name' => 'required|max:33'
        ]);

    	Category::create($request->all());

    	return redirect()->route('categories.index');
    }

    public function update(Request $request, $category)
    {
        $this->validate($request, [
            'name' => 'required|max:33'
        ]);

        $category = Category::ForAuthedUser()->findOrFail($category);

    	$category->name = $request->name;
    	$category->save();

    	return redirect()->route('categories.index');
    }

    public function destroy($category)
    {
        Category::ForAuthedUser()->findOrFail($category)->delete();

    	return redirect()->route('categories.index');
    }
}

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')
	
	<div class="overflow-x-scroll">
		<table>

			<tr class="w-full">
				<th class="w-1/6 border-b-2 p-2 border-blue-lighter">Name</th>
				<th class="w-1/6 bg-grey-lighter"></th>
			</tr>
			
			@foreach($categories as $category)	
			<tr class="w-full">
				<td class="w-1/6 p-2 text-center">{{ $category->name }}</td>
				<td class="w-1/6 p-2 text-center flex justify-between">

					{{-- <form method="GET" action="{{ route('categories.edit', [$expense->id]) }}">
						<button class="btn text-grey-dark hover:bg-blue-lighter mx-2">E</button>
					</form>

					<form method="POST" action="{{ route('transactions.destroy', [$expense->id]) }}">
						{{ csrf_field() }}
						{{ method_field('delete') }}
						<button type="submit" class="btn text-grey-dark hover:bg-red-lighter mx-2">D</button>
					</form> --}}
				</td>
			</tr>
			@endforeach

		</table>		
	</div>

	{{-- {{ $transactions->links() }} --}}
@endsection

resources/views/categories/show.blade.php
@extends('layouts.app')

@section('content')
			  
  <div class="md:flex">
    <div class="w-1/2 m-3 mb-6">
      <h3 class="text-base text-grey-darker py-2 border-b-2">Category Name</h3>
      <p class="text-lg pt-3">{{ $category->name }}</p>
    </div>
  
  {{-- <div class="md:flex">
    <div class="m-3 mb-6 mt-5">
      <a href="{{ route('transactions.edit', [$transaction->id]) }}" class="btn btn-blue no-underline">Edit</a>
    </div>

    <div class="m-3 mb-6 mt-1">
    	<form method="post" action="{{ route('transactions.destroy', [$transaction->id]) }}">
    		{{ csrf_field() }}
    		{{ method_field('delete') }}
	    	<input type="submit" class="btn btn-red no-underline cursor-pointer" value="Delete">
    	</form>
    </div> --}}
  </div>

@endsection